<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Tsinswreng.CsSql/Tsinswreng.CsSql.csproj" />
	</ItemGroup>

	<ItemGroup>
		<!-- 強類型 Id 源生成器模板 -->
		<AdditionalFiles Include="Domains/UInt128Template.typedid" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Tsinswreng.CsTreeTest" Version="0.1.1-alpha" />
		<PackageReference Include="StronglyTypedId" Version="1.0.0-beta08" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
	</ItemGroup>
</Project>
